CREATE DATABASE trab;

USE trab;

CREATE TABLE alunos (
matricula INT AUTO_INCREMENT PRIMARY KEY,
primeiro_nome VARCHAR(50) NOT NULL,
sobrenome VARCHAR(50) NOT NULL,
curso VARCHAR(50) NOT NULL,
data_matricula TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
tel VARCHAR(11)
);
